version: '3'

services:

  postgres :
    container_name: postgres
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data/dev/postgres:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}


networks:
  dev-network:
    driver: bridge
